name: autoupdate
on:
  # push: {}

  push:
    branches:
      - main

  # schedule:
    # - cron: '*/1 * * * *'
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    steps:
        - name: Auto Update
          uses: chinthakagodawita/autoupdate@v1.7.0  
          env:
            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
