name: autoupdate
on:
  # push: {}

  push:
    branches:
      - main

  # schedule:
    # - cron: '*/1 * * * *'
jobs:
  # autoupdate:
  #   name: autoupdate
  #   runs-on: ubuntu-22.04
  #   steps:
  #       - name: Auto Update
  #         uses: chinthakagodawita/autoupdate@v1.7.0  
  #         env:
  #           GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically update PR
        uses: adRise/update-pr-branch@v0.7.0
        with:
          token: ${{ secrets.ACTION_USER_TOKEN }}
          base: 'main'
          required_approval_count: 0
          require_passed_checks: true
          sort: 'created'
          direction: 'desc'
          require_auto_merge_enabled: false
