name: autoupdate
on:
  # push: {}

  push:
    branches:
      - main

  # schedule:
    # - cron: '*/1 * * * *'
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    steps:
        - name: Auto Update
          uses: chinthakagodawita/autoupdate@v1.7.0  
          env:
            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  # autoupdate:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Automatically update PR
  #       uses: adRise/update-pr-branch@v0.7.0
  #       with:
  #         token: '${{ secrets.GITHUB_TOKEN }}'
  #         base: 'main'
  #         required_approval_count: 0
  #         require_passed_checks: false
  #         sort: 'created'
  #         direction: 'desc'

  # update-branch:
  #   # permissions:
  #   #   id-token: write
  #   #   contents: read
  #   #   issues: write
  #   #   pull-requests: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: lcdsmao/update-branch@v3
  #       with:
  #         # Or use personal access token
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         # One of MERGE, SQUASH, REBASE (default: MERGE)
  #         autoMergeMethod: SQUASH
  #         # Required approvals from all requested reviewers
  #         allRequestedReviewersMustApprove: false
