name: Check_

on:
  pull_request:
    branches:
      - main  # Change this to your project's main branch

jobs:
  check_:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR
      uses: JJ/github-pr-contains-action@releases/v13
      with:
        github-token: ${{github.token}}
        diffDoesNotContain: "TODO|to do|with restricted_access"
